name: "my work flow"

on: push
  # push:
  #   branches:
  #     - 'feature/**'

permissions:          
  id-token: write        
  contents: read       
  
jobs:
  TerraformInit: 
    name: Initva
    runs-on: aman-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0 

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.8.5
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
              client-id: 7bba9e59-4de0-4840-831b-1bd5e39fd291
              tenant-id: 5792dd07-62dc-48ac-a7ae-855280503fdb
              subscription-id: 76095b6e-0585-402e-8e43-281835aebfd1

    

      
      
