name: "my work flow"

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'feature/**'

permissions:          
  id-token: write        
  contents: read       
  
jobs:
  TerraformInit: 
    name: Init and plan
    runs-on: aman-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0 

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.8.5
          
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
              client-id: 7bba9e59-4de0-4840-831b-1bd5e39fd291
              tenant-id: 5792dd07-62dc-48ac-a7ae-855280503fdb
              subscription-id: 76095b6e-0585-402e-8e43-281835aebfd1


      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
  jobs:
      name: Run tfsec
      runs-on: ubuntu-latest
      needs: TerraformInit 
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Run tfsec
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            args: --format csv --out tfsec_results.csv
  TerraformApply: 
     name: Apply
     runs-on: aman-runner
     environment: prod
     needs: TerraformInit
     steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0 
    
        - name: Install Terraform
          uses: little-core-labs/install-terraform@v2.0.0
          with:
            version: 1.8.5
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
                client-id: 7bba9e59-4de0-4840-831b-1bd5e39fd291
                tenant-id: 5792dd07-62dc-48ac-a7ae-855280503fdb
                subscription-id: 76095b6e-0585-402e-8e43-281835aebfd1
        
        - name: Terraform Init
          id: init
          run: terraform init -input=false  
      
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false
          continue-on-error: true
    
        - name: Terraform Apply
          id: Apply
          run: terraform apply --auto-approve
          continue-on-error: true
    


      
      
