name: "my work flow"

on: push
  # push:
  #   branches:
  #     - 'feature/**'

jobs:
  TerraformInit: 
    name: Initva
    runs-on: aman-runner
    steps:
     - name: aman
       run: echo "aman runner ka workflow"
     - name: aman
       run: echo "aman workflow"
    
