name: "my work flow"

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  TerraformInit: 
    name: Initva
    runs-on: aman-runner
    steps:
     - name: aman runner ka workflow
       run: echo aman runner ka workflow
    
